/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  sections?: Array<
    {
      _key: string
    } & Section
  >
}

export type Cta = {
  _id: string
  _type: 'cta'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  content?: string
}

export type Form = {
  _id: string
  _type: 'form'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  inputs?: Array<
    | ({
        _key: string
      } & FormQuestion)
    | ({
        _key: string
      } & FormChoice)
    | ({
        _key: string
      } & FormBoolean)
  >
}

export type Section = {
  _type: 'section'
  heading?: string
  content?: string
}

export type Reviews = {
  _id: string
  _type: 'reviews'
  _createdAt: string
  _updatedAt: string
  _rev: string
  author?: string
  avatar?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  content?: string
  source?: 'Google' | 'Facebook' | 'Inne'
  sourceLink?: string
  score?: '1' | '1.5' | '2' | '2.5' | '3' | '3.5' | '4' | '4.5' | '5'
  orderRank?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Gallery = {
  _type: 'gallery'
  images?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    aspect?: '3:4' | 'square' | '16:9' | 'panorama' | 'auto'
    _type: 'image'
    _key: string
  }>
}

export type ContactInfo = {
  _id: string
  _type: 'contactInfo'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  emails?: Array<string>
  phoneNumber?: Array<string>
  socials?: Array<string>
  location?: string
}

export type Services = {
  _id: string
  _type: 'services'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  sections?: Array<
    {
      _key: string
    } & SectionColor
  >
}

export type Features = {
  _id: string
  _type: 'features'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  sections?: Array<
    {
      _key: string
    } & Section
  >
}

export type AboutPages = {
  _id: string
  _type: 'aboutPages'
  _createdAt: string
  _updatedAt: string
  _rev: string
  shortTitle?: string
  shortSubTitle?: string
  shortDescription?: string
  longTitle?: string
  longDescription?: string
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type FormChoice = {
  _type: 'formChoice'
  question?: string
  choices?: Array<string>
  required?: boolean
  multiSelect?: boolean
}

export type FormBoolean = {
  _type: 'formBoolean'
  question?: string
  required?: boolean
}

export type FormQuestion = {
  _type: 'formQuestion'
  question?: string
  required?: boolean
  long?: boolean
}

export type SectionColor = {
  _type: 'sectionColor'
  title?: string
  description?: string
  background?: Color
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type PortfolioTag = {
  _id: string
  _type: 'portfolioTag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type PortfolioSlug = {
  _id: string
  _type: 'portfolioSlug'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  tags?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'portfolioTag'
  }>
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    aspect?: 'square'
    _type: 'image'
  }
  description?: string
  mainSection?: Section
  showOnHomepage?: boolean
  sections?: Array<
    {
      _key: string
    } & Section
  >
  gallery?: Gallery
  orderRank?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type PortfolioPages = {
  _type: 'portfolioPages'
  longTitle?: string
  longDescription?: string
  shortTitle?: string
  shortDescription?: string
}

export type Tags = Array<
  {
    _key: string
  } & Tag
>

export type Tag = {
  _type: 'tag'
  value?: string
  label?: string
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Faq
  | Cta
  | Form
  | Section
  | Reviews
  | SanityImageCrop
  | SanityImageHotspot
  | Gallery
  | ContactInfo
  | Services
  | Features
  | AboutPages
  | FormChoice
  | FormBoolean
  | FormQuestion
  | SectionColor
  | Color
  | PortfolioTag
  | PortfolioSlug
  | Slug
  | PortfolioPages
  | Tags
  | Tag
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
